name: git-auto-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    permissions:
     contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Use git-auto-commit-action
        id: "auto-commit-action"
        uses: ./

      - name: "changes detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: ".svg"