name: git-auto-commit

on:
  schedule: [{cron: "0 23 * * *"}]
  workflow_dispatch:


env:
  GIT_NAME: "JHKoder"
  GIT_EMAIL: "jeonghun.kang.dev@gmail.com"


jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check if file modified today
        id: check-file
        run: |
          today=$(date +'%Y-%m-%d')
          if [[ $(git log -1 --format="%cd" --date="short" --  github-metrics.svg) == $today ]]; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: git auto update
        if: env.modified == 'true'
        run: |
          git config user.name ${{ env.GIT_NAME }}
          git config user.email ${{ env.GIT_EMAIL }}
          git pull origin main
          git checkout origin/main -- github-metrics.svg
          cp github-metrics.svg temp_github-metrics.svg
          git rm github-metrics.svg
          
          delete_commit_hash=$(git rev-parse HEAD)
          git commit -m "Auto updating... (delete)" --author="${{ env.GIT_NAME }} <${{ env.GIT_EMAIL }}>"
          git pull origin main
          mv temp_github-metrics.svg github-metrics.svg
          git add github-metrics.svg
          git commit -m "Auto updating... (add)" --author="${{ env.GIT_NAME }} <${{ env.GIT_EMAIL }}>"
          git cherry-pick $delete_commit_hash
          git push origin HEAD