name: git-auto-commit

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: JHKoder
          author_email: jeonghun.kang@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}