name: git-auto-commit

on:
  schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16


      - name: Check if file modified today
        id: check-file
        run: |
          today=$(date +'%Y-%m-%d')
          if [[ $(git log -1 --format="%cd" --date="short" --  github-metrics.svg) == $today ]]; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Remove existing file
        if: env.modified == 'true'
        run: |
          rm -f github-metrics.svg
          cp github-metrics.svg /path/to/new/github-metrics.svg
          git add github-metrics.svg

      - name: Commit changes with new author
        if: env.modified == 'true'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "JHKoder"
          author_email: "jeonghun.kang@gmail.com"
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}