name: git-auto-commit

on:
  schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check if file modified today
        id: check-file
        run: |
          today=$(date +'%Y-%m-%d')
          if [[ $(git log -1 --format="%cd" --date="short" -- ./path/to/github-metrics.svg) == $today ]]; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Commit changes with new author
        run: |
          git config user.name "JHKoder"
          git config user.email "jeonghun.kang@gmail.com"
          git add ./path/to/github-metrics.svg
          git commit -m "Auto updating my readme" --author="JHKoder <jeonghun.kang@gmail.com>"
          git push --token ${{ secrets.METRICS_TOKEN }}