name: Metrics
on:
  schedule: [{cron: "0 23 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JHKoder
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_ignored: html,css,js
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - name: Youtube
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          delay: 120
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLIqivMolpkyMyS8U1e1V0fJPgw-hZZrDO
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugins_errors_fatal: yes
          plugin_music_user: Jeonghun kang
